### ISSUE TITLE
MultiQC bug 

### ISSUE THREAD

**Issue by felloumi** [skchronicles/RNA-seek#26]
Hello,

I got an issue when running rnaseq_multiqc for a new project:
>>--------
multiqc : Oops! The 'kraken' MultiQC module broke...
  Please copy the following traceback and report it at https://github.com/ewels/MultiQC/issues
  If possible, please include a log file that triggers the error - the last file found was:
    ......trim.kraken_bacteria.taxa.txt
============================================================
Module kraken raised an exception: Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/multiqc/multiqc.py", line 569, in run
    output = mod()
  File "/usr/local/lib/python3.6/dist-packages/multiqc/modules/kraken/kraken.py", line 60, in __init__
    self.sum_sample_counts()
  File "/usr/local/lib/python3.6/dist-packages/multiqc/modules/kraken/kraken.py", line 134, in sum_sample_counts
    self.kraken_sample_total_readcounts[s_name] = round(float(row['counts_rooted']) / (row['percent'] / 100.0))
ZeroDivisionError: float division by zero
<<------

Running the new version of multiqc (1.12) fixed the problem. The rnaseq pipeline should use the 1.12 version or the latest.

@felloumi

**Comment by skchronicles** [comment]
Hey @felloumi,

Thank you for reporting this issue. 

Yes, this appears to be a bug reported in the version of MultiQC we are using. It is documented here: https://github.com/ewels/MultiQC/issues/1276

It has been fixed in newer versions of the tool. When I have some free time, I will build and test a new `MultiQC/1.12` docker image. Just as a side note, I am also going to bundle the MultiQC config file with RNA-seek. At the current moment, it is pulling the config file remotely. This is a small file, so we can bundle it with the GH repo.

I will keep you updated on the progress. Have a great day!

Best Regards,
@skchronicles

**Comment by felloumi** [comment]
Thank you a @skchronicles

**Comment by skchronicles** [comment]
@felloumi This issue has been resolved (version 1.5.0). Please use the latest version of the pipeline, and have a great day!
